### ISSUE TITLE
how reload paging when comment

### ISSUE THREAD

**Issue by buiphu** [michaelbromley/ng2-pagination#10]
i used ionic 2 and angular2 for build app
i used ng2-pagination for paging comment

when i post new comment. i used ` this.comments.unshift(comment);` for insert first comment
how in template will show this comment in first and page 1.

i must be next page 2 then pervious page 1 , it show that

i want  new comment show in first and in page1 , don't next page2 then pervious page1

**Comment by michaelbromley** [comment]
Hi,

I'm not sure I completely understand the issue here. Do you mean that when you `unshift()` an item onto the array, it does not show up in the list until you switch to page 2 and then back to page 1?

I am currently doing a major refactor and will be adding many more tests, so I can include this as a test case.

**Comment by buiphu** [comment]
"Do you mean that when you unshift() an item onto the array, it does not show up in the list until you switch to page 2 and then back to page 1?"
yes. 

how fix it

**Comment by michaelbromley** [comment]
Okay. As I said, I am working on this right now so I will add this case to my unit tests and update this issue once there is a fix.

**Comment by buiphu** [comment]
thanks so much. when are you finish  update and fix it you can send for me in issue or you can note in github

**Comment by michaelbromley** [comment]
Hi, please see the latest version (beta.1) - this should be working now.
