### ISSUE TITLE
(feat): Possibility of set the text for directionLinks

### ISSUE THREAD

**Issue by rafaelss95** [michaelbromley/ng2-pagination#103]
**Angular 2 version**:
2.2.1
**ng2-pagination version**:
1.0.1

In fact it isn't an issue. It's a feature request.

Actually I have to build my custom component only to modify the words in `[directionLinks]`.

Would be great if we could set the text for the `[directionLinks]` and also, if possible, add `[boundaryLinks]` as in your pagination directive for AngularJs.

Something like this:

```
<pagination-controls  id="some_id"
                      (pageChange)="pageChanged($event)"
                      maxSize="9"
                      directionLinks="true"
                      boundaryLinks="true"
                      previousText="<"
                      nextText=">"
                      autoHide="true">
</pagination-controls>
```

Thanks in advance.

**Comment by michaelbromley** [comment]
Hi,

This is a good point and in fact I am considering changing the default template, and maybe dropping the text altogether.

Re boundary links, I had considered them unnecessary because the first and last page is *always* displayed, so boundary links bring no new functionality. Does that make sense? If you can think of a good counter argument, I am open to feedback.

**Comment by rafaelss95** [comment]
@michaelbromley, yeah, in fact, boundary links makes no sense at all.

**Comment by michaelbromley** [comment]
Track in #106
