### ISSUE TITLE
Search Function

### ISSUE THREAD

**Issue by Sevensnake** [michaelbromley/ng2-pagination#117]
Hi I added a search filter. almost similar to the search filter you have [http://michaelbromley.github.io/ng2-pagination/#/advanced](url)  But does not seem to search outside of the viewable objects in your table. Do you mind sharing the search filter you used in the demo. Thanks.

**Comment by michaelbromley** [comment]
Sure, the filter pipe is part of this repo: [source](https://github.com/michaelbromley/ng2-pagination/blob/4200c7b12317e871a02828ca93041d515f987b85/docs/src/string-filter.pipe.ts).

You can see how it is used [here](https://github.com/michaelbromley/ng2-pagination/blob/4200c7b12317e871a02828ca93041d515f987b85/docs/src/components/advanced-example/advanced-example.component.html#L73)

From your description it sounds like you possibly have the pipes in the wrong order, i.e. you are paginating and then filtering, rather than filtering and then paginating.
