### ISSUE TITLE
Cannot read property 'emit' of undefined

### ISSUE THREAD

**Issue by alsoicode** [michaelbromley/ng2-pagination#123]
**Angular 2 version**: 2.4.6

**ng2-pagination version**: 2.0.0

**Description of issue**: Exception error when using custom template from example code

**Steps to reproduce**: Copy/paste example custom template code into an existing component

**Expected result**: Next/Previous links work as expected using custom template markup

**Actual result**: Exception is thrown: Cannot read property 'emit' of undefined

**Demo**: (if possible, edit [this Plunker demo](http://plnkr.co/edit/JVQMPvV8z2brCIzdG3N4?p=preview) and paste the link to your fork)

Any relevant code:
```
    <pagination-template #p="paginationApi" (pageChange)="pageChange.emit($event)">
        <div class="pagination-previous" [class.disabled]="p.isFirstPage()">
          <a *ngIf="!p.isFirstPage()" (click)="p.previous()">
            < </a>
        </div>

        <div *ngFor="let page of p.pages" [class.current]="p.getCurrent() === page.value">
          <a (click)="p.setCurrent(page.value)" *ngIf="p.getCurrent() !== page.value">
            <span>{{ page.label }}</span>
          </a>
          <div *ngIf="p.getCurrent() === page.value">
            <span>{{ page.label }}</span>
          </div>
        </div>

        <div class="pagination-next" [class.disabled]="p.isLastPage()">
          <a *ngIf="!p.isLastPage()" (click)="p.next()"> > </a>
        </div>
      </pagination-template>
```

I have worked around this issue by adding an `onPageChanged($event)` handler on my component. Am I missing an implementation detail somewhere?

Thanks!

**Comment by michaelbromley** [comment]
Hi,

The example code is assuming your custom component has an EventEmitter named `pageChange`. Since you have not defined one, you get the "Cannot read property 'emit' of undefined" error.

The solution really depends on how you wish to use the component. If it will be a re-usable component, I would advise re-emitting the pageChange event with your own EventEmitter (note that you can name it whatever you like). If you want to handle the pageChange event internally, then you existing solution of calling `onPageChange($event)` is fine.

**Comment by alsoicode** [comment]
Thanks for the explanation. In my case, I just added a handler for the event and we're all good.
