### ISSUE TITLE
Pagination Links Cursor Not Set To Pointer

### ISSUE THREAD

**Issue by winni4eva** [michaelbromley/ng2-pagination#131]
**Angular 2 version**:
2.2.0
**ng2-pagination version**:
2.0.1
**Description of issue**:
Pagination links css Cursor not set to pointer

Is there a way to add custom styles

**Comment by michaelbromley** [comment]
I guess it is not set to `pointer` in the css because it uses `<a>` tags for the links, which should cause the browser to automatically use `pointer`.

To answer your question: yes - see [this part of the docs](https://github.com/michaelbromley/ng2-pagination/tree/bbb1420112d4d26975b32f5e026c594b06ebc50a#styling)

**Comment by winni4eva** [comment]
thanks for the tip..
