### ISSUE TITLE
Problem with using dynamic ID and CurrentPage 

### ISSUE THREAD

**Issue by edwardpayton** [michaelbromley/ng2-pagination#134]
**Angular 2 version**: v2.4.8

**ng2-pagination version**: v2.0.1

**Description of issue**: 

I'm using ng2-paginate in a table component, there are multiple table components per page (so multiple pagers). The ID and currentPage config options need to be dynamic.

**Steps to reproduce**:

1st attempt to solve:
The pipe: <tr *ngFor="let object of objects | paginate: { id: idVar, itemsPerPage: 10, currentPage: p }">
And the component: <pagination-controls id="idVar" (pageChange)="p = $event">
This fails because the id expects a string

2nd attempt:
The pipe: <tr *ngFor="let object of objects | paginate: pagerConfig">
The component: <pagination-controls id="{{pagerConfig.id}}" (pageChange)="pagerOnChangeEv">
My table component:
```code
pagerConfig: Object = {
      id: `pager-${this.tableName}`,
      itemsPerPage: 10,
      currentPage: `${this.tableName}-p`
    }
pagerOnChangeEv: string = `${this.tableName}-p = $event`;
```
This fails for reasons that escape me. The 'objects' data loads, but the *ngFor doesn't display it, the pager displays the correct number of pages.

**Expected result**:
Possible to use a dynamic id and currentPage variable.

**Demo**: 
Plunkr of my 2nd attempt: http://plnkr.co/edit/1zArFnEy81czjVwfduN3?p=preview

All the best
Edward

**Comment by michaelbromley** [comment]
Hi,

Your first approach is closest to the mark. To me it seems that the issue there is this bit: `id="idVar"` - here you are setting the id to be the literal string "idVar". To bind to the value of `idVar`, you would write: `[id]="idVar"` (note the square brackets).

However, since you are binding the `currentPage` to the variable `p`, you would need to ensure that all the other pagination instances bind the `currentPage` to a *different* variable, otherwise paging one instance will change the currentPage for all the instances.

The second attempt has a couple of weird things going on:

1. "currentPage: `${this.tableName}-p`" - `currentPage` has the type `number`, but you are setting it to a string. The pipe will not know what to do with this!
2. `(pageChange)="pagerOnChangeEv"` - when you bind to an event with parentheses, Angular expects either a method or an expression. Here you are trying to bind to a string containing an expression. I am pretty sure this is invalid.

[Here is a working version](http://plnkr.co/edit/QMszAbozwa3i7BxixjDN?p=preview) of your plunker demo.

**Comment by edwardpayton** [comment]
Thanks for coming back so quickly Michael - I misunderstood a few things, thanks for clearing it all up.

It's all working now with two tables on the page and pagination working for each. 

Great module, highly recommended!

**Comment by michaelbromley** [comment]
Cool, glad you got it sorted! 👍
