### ISSUE TITLE
Loading Individual Page Results Rather than Entire Data Set

### ISSUE THREAD

**Issue by darrenbrett** [michaelbromley/ng2-pagination#142]
Hi Michael,

Thanks for this great Angular module/plugin. It's much appreciated!

I have successfully set up ng2-pagination to work in my Angular 2 app. Right now I am pulling in all records and storing them in memory because I'm a little unclear on how to actually edit the functionality to handle a real api call where the call is made for each page, rather than once for the entire data set. I looked at your example server-side demo, but I'm still unclear. I'm hoping you can offer some clarity. To offer a little more specificity, the call to my api from my service file looks like this:

```
    getByCategory(stage: string) {
        const q = encodeURIComponent(category);
        return this.http.get
        (`https://api.someurl.com/${this.ver}/customers/category/${q}&apikey=${this.key}`)
            .map((response: Response) => response.json())
            .catch(this._errorsHandler);
    }
        _errorsHandler(error: Response) {
        console.error(error);
        return Observable.throw(error.json().error || 'Server error');
```

Then, in my component I have this:

```
    ngOnInit() {
       this.streamService.getByCategory('consulting')
            .subscribe(resRecordsData => this.records = resRecordsData,
            responseRecordsError => this.errorMsg = responseRecordsError);
    }
```

In the view for the component I am using ng2-pagination like this:

` <tr *ngFor="let record of records | paginate: { id: 'customers', itemsPerPage: 12, currentPage: page, totalItems: total }">`

```
            <pagination-controls class="paginator" (pageChange)="getPage($event)" id="customers"
                    maxSize="15"
                    directionLinks="true"
                    autoHide="true">
            </pagination-controls>
```

Can you help me understand how I would edit the component to handle making a call for each page loaded, where a user can still navigate to different results pages, without all the records being pulled in one go?

And if you're not able to help with this, if you have a reference to a github example using a real (or realistic mock) api call, I'd love to have a look. Thanks!

**Comment by michaelbromley** [comment]
Hi,

The main requirement is that the API you are consuming must support pagination. For example, the API might accept parameters such as "top", "skip" or similar which tell the server how many items to serve in response.

A typical paginated API response would include an array of items (the items on that page) and then some information about the total number of items in the collection. See again the [example in the docs](https://github.com/michaelbromley/ng2-pagination#server-side-paging).

If your API does not support paging, then I'm afraid this module cannot help with that. You either need to modify the API or ask someone to do it if it is beyond your control. However, many APIs do support this, but note that they may differ in the way they deliver the "total items" data. E.g. the [Wordpress API](https://developer.wordpress.org/rest-api/using-the-rest-api/pagination/) includes it as a response header rather than as part of the body.

I hope that helps. Let me know if you have further questions.

**Comment by darrenbrett** [comment]
Hi Michael,

That helps a lot, yes. It does clarify for me that the API will need to handle much of this - rather than the front-end Angular app. In my situation, we're using a Node/MongoDB backend. And it does offer functions like skip. So I will check in with my server person to handle this. Thanks.
