### ISSUE TITLE
Hide "You're on page 1"

### ISSUE THREAD

**Issue by KhaosTheory1012** [michaelbromley/ng2-pagination#3]
"You're on page 1"

Is there currently a way to hide this text or to change it/position it/its value elsewhere?

Looks like this atm and Id like to have it inline:
"Previous page"
You're on page 1
"Page 2" "Next page"

Also having an issue with pagecontrols::
<pagination-controls></pagination-controls>
can't be set before the Pagepipe I am always getting a page not set error
Helping myself out with ngIf

**Comment by aicokleinovink** [comment]
How is this issue closed? I'm having the exact same thing??

**Comment by michaelbromley** [comment]
The current template is taken directly from the Foundation 6 framework (simply because I am using Foundation 6 in a current project). In the Foundation 6 CSS, these "You're on page" bits are hidden for screen and only used by screen readers.

I intend to make the template configurable, but I don't know how to do that yet.
