### ISSUE TITLE
[Feature] Templating the Collection

### ISSUE THREAD

**Issue by RicardoVaranda** [michaelbromley/ng2-pagination#31]
Hey guys was just wondering if its possible to template the elements which we are paginating so for example:

```
for (let i = 1; i <= 10; i++) {
            this.collection.push(`
               <h5>Step ${i}</h5>
                
            `);
        }
```

This prints out < h5 >Step 1..10< /h5 >

Instead of a larger text 
<h5>Step 1</h5>

hope you get what I mean, is it possible to alter this behavior so that it does in fact use styling.

**Comment by RicardoVaranda** [comment]
@michaelbromley

**Comment by michaelbromley** [comment]
Hi,

This issue is not really specific to this library - it's a general Angular2 question. 

You can achieve what you describe by binding to the `innerHTML` property of the list element:

```html
<li *ngFor="let item of collection | paginate: { itemsPerPage: 10, currentPage: p }" [innerHTML]="item"></li>
```

Note that you may need to think about how Angular will sanitize HTML in the future if you use this approach - see [this note in their changelog](https://github.com/angular/angular/blob/master/CHANGELOG.md#other-breaking-changes)

**Comment by RicardoVaranda** [comment]
Thanks very much for the explanation mate.
