### ISSUE TITLE
Remove deprecated clip

### ISSUE THREAD

**Issue by ShiftySituation** [michaelbromley/ng2-pagination#32]
Clip has been deprecated, should use clip-path instead in Template.ts.

[https://developer.mozilla.org/en-US/docs/Web/CSS/clip](url)

**Comment by michaelbromley** [comment]
Thanks for the report - I had no idea about it, since I just took that css from Zurb Foundation 6.

Looking at the MDN docs, it looks like even though "clip" is deprecated, it is [supported in all major browsers](https://developer.mozilla.org/en-US/docs/Web/CSS/clip#Browser_Compatibility).

On the other hand, "clip-path" has [relatively poor support](http://caniuse.com/#search=clip-path) at this time.

Therefore I'll leave it as-is for now until things change.
