### ISSUE TITLE
Show all items

### ISSUE THREAD

**Issue by Miloune** [michaelbromley/ng2-pagination#39]
Hi,

Thanks for your work. I found an issue:

When you want to show all items, you have to put 0 as itemsPerPage. The problem is in pagination control. You can see "infinte button" in navigation control.

You can reproduce this in your [plnk](http://plnkr.co/edit/JVQMPvV8z2brCIzdG3N4?p=preview) by set itemsPerPage at 0.
Overwhise you can do it too in your ["Full example"](http://michaelbromley.github.io/ng2-pagination/).

Thanks

**Comment by michaelbromley** [comment]
Hi,

To show all items, rather than setting `itemsPerPage` to 0, you should set it to a very large number, e.g. `Number.MAX_SAFE_INTEGER;`. The only reason setting it to 0 works at all is because internally, it substitutes the 0 for `Number.MAX_SAFE_INTEGER;` when slicing the array.

The page links of course get messed up because you are performing a "divide by zero" operation, which results in `infinity`.
