### ISSUE TITLE
Help wanted with ng-content

### ISSUE THREAD

**Issue by Miloune** [michaelbromley/ng2-pagination#55]
**Angular 2 version**: 2.0.0-rc.3

**ng2-pagination version**: 0.3.1

**Description of issue**: I'm trying to make a component who add pagination controls to my table, but my pagination controls seems to not doing anything.
What i'm doing wrong?

**Steps to reproduce**: See my Plnkr.

**Expected result**:
Get pagination page

**Actual result**:
Only the next button appear then disappear when we click on.

**Demo**: http://plnkr.co/edit/ToZeijKVoq7snVaf11TA?p=preview

**Comment by michaelbromley** [comment]
Hi,

There were 2 issues:

1) You were providing the `PaginationSerive` twice - both in the App component, and in the Table component. The service needs to be a single instance shared between the controls and the paginate pipe, but the fact you declare it again in the Table component means a new instance is created at that point in the component tree. 

Removing the "providers" property of the Table component metadata fixes this, since then the PaginatePipe and the PaginationControlsCmp will both use the same instace of PaginationService (the one provided in the App component)

2) A custom template was defined inside the controls. 

See the fixed plunk: http://plnkr.co/edit/UQd7fPZeIEAaxqU9aN2T?p=preview
