### ISSUE TITLE
Error in installing pagination

### ISSUE THREAD

**Issue by rameshbas** [michaelbromley/ng2-pagination#60]
Hi, thanks for contributing!

This project is maintained in my spare time, so in order to help me address your issue as quickly as 
possible, please provide as much of the following information as you can.

-- Michael 

=======

**Angular 2 version**:"@angular/common": "2.0.0-rc.4",

**ng2-pagination version**: latest

**Description of issue**: Gives some warning errors when I issue the command
npm WARN optional Skipping failed optional dependency /chokidar/fsevents:
npm WARN notsup Not compatible with your operating system or architecture: fsevents@1.0.14
npm WARN angular2-quickstart@1.0.0 No description
npm WARN angular2-quickstart@1.0.0 No repository field.

**Steps to reproduce**:
npm install ng2-pagination
**Expected result**:
clean install
**Actual result**:
I checked it is there in node_modules\ng2-pagination
in my component I put in my component
import {PaginatePipe, PaginationControlsCmp, PaginationService} from 'ng2-pagination';
localhost/:25 Error: Error: XHR error (404 Not Found) loading http://localhost:3001/ng2-pagination(…)

I also tried putting the js file in my index.html:
<script src="https://rawgit.com/michaelbromley/ng2-pagination/master/dist/ng2-pagination-bundle.js"></script>
then it works! 

Any relevant code:
```

```

**Comment by michaelbromley** [comment]
Hi,

The warnings generated by npm when installing are nothing to do with this module. As you can see from the messages, they relate to other packages using `fsevents` and the last two are there just because the `angular2-quickstart` package.json file does not include a description or repository field, which npm expects it to. Anyway, they are just warnings and do not indicate anything to worry about really.

The real issue is probably a config thing with the systemjs loader. You need to make sure you configure it to know where the ng2-pagination-bundle.js file resides. Check out the Systemjs docs if that is the case.
