### ISSUE TITLE
How to do animation on page being changed ? 

### ISSUE THREAD

**Issue by huskywhale** [michaelbromley/ng2-pagination#75]
**2.0 release**:

**ng2-pagination version: 0.4.1**:

I was wondering how to trigger an action to do animations. any help would be helpful.

**Comment by michaelbromley** [comment]
Hi,

I've got no experience with animations in Angular 2. So far in my apps I've just been using regular CSS transitions based on adding/removing classes. Here's an article I read the other day which explains how the animations should work: http://blog.thoughtram.io/angular/2016/09/16/angular-2-animation-important-concepts.html

Since this is a general Angular 2 question, I'll close this issue.
