### ISSUE TITLE
getPage() always give undefined as page.

### ISSUE THREAD

**Issue by kodeine** [michaelbromley/ng2-pagination#78]
**Angular 2 version**:
rc 5 

**ng2-pagination version**:
latest

**Description of issue**:
in console i always get NaN
```ts
    filters:Object = {};

    p: number = 1;
    total: number = 30;
...
...
...
    getPage(page:any) {
        console.log('page', page);
    }
```

```html
<md-list-item *ngFor="let item of users | async | paginate: { id: 'server', itemsPerPage: 1, currentPage: p, totalItems: total }">
....
....
....
    <pagination-controls (pageChange)="getPage($event)" id="server"></pagination-controls>
```

**Comment by michaelbromley** [comment]
You probably need to wrap parens around the async pipe:

```
<md-list-item *ngFor="let item of (users | async) | paginate: { id: 'server', itemsPerPage: 1, currentPage: p, totalItems: total }">
```

**Comment by kodeine** [comment]
@michaelbromley same thing, i dont even see the page numbers.

**Comment by HristoKolev** [comment]
Can you replicate it in a plunker?

**Comment by kodeine** [comment]
@HristoKolev i dont know if its easily possible to replicate in plunkr but i am using [angular2 starter](https://github.com/AngularClass/angular2-webpack-starter)

**Comment by kodeine** [comment]
anyone can help?

**Comment by michaelbromley** [comment]
@kodeine I'm afraid I don't have the time to try to reproduce the issue and then debug it. The fact is, the code you posted originally looks to me like it should work. It is almost identical to the [working demo](https://github.com/michaelbromley/ng2-pagination/blob/358b10e5c6a0a14c2207427193b5ab1aed358756/demo/src/examples/server-example-cmp.html#L2). 

Therefore the issue must lie elsewhere, in code which you *did not* post. The only way for me (or anyone else) to figure out what that code might be, is to spend time attempting to reproduce the issue. This may take a long time, depending on the origin of the bug. The person best positioned to do this work is you, since you have both the best knowledge of your code base, and also the greatest motivation to spend time doing so.

This is a long-winded way of saying that this issue is not really actionable for me unless you provide a minimal demo which reproduces the issue. Try  [this Plunker demo](http://plnkr.co/edit/JVQMPvV8z2brCIzdG3N4?p=preview)  as a basis.

**Comment by kodeine** [comment]
@michaelbromley 
i was able to fix the error, i was using immutable List which paginator didnt understand as data. So all i needed to do was data.toArray() without using async pipe and it worked.
